import './fading-text.js';
import './goingUp-text.js';
import './fading-image.js';
import './fullscreen-scroll.js';
import './fixed-attachment.js';
import './zoom-area.js';
import './statistics-chart.js';
import './circle-cursor.js';
import './2dmap-zoom-and-moving.js';
